# MySQL (default setup).  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql
# On MacOS X:
#   gem install mysql -- --include=/usr/local/lib
# On Windows:
#   gem install mysql
#       Choose the win32 build.
#       Install MySQL and put its /bin directory on your path.
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

#<% get_socket = lambda{ ["/opt/local/var/run/mysql5/mysqld.sock",
#                         "/opt/lampp/var/mysql/mysql.sock",
#                         "/var/run/mysqld/mysqld.sock",
#			 "/var/lib/mysql/mysql.sock"].\
#                        detect{|p| File.exists?(p)} } %>

common: &common
   adapter: mysql
   host: 127.0.0.1
   username: tarantula
   password: 123456
   encoding: utf8

development:
   database: tarantula_devl
   <<: *common

test:
   database: tarantula_test
   <<: *common

production:
   database: tarantula_prod
   <<: *common

